trigger:
  - main

pool:
  name: 'YourSelfHostedAgentPool'

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '5.x' # Use the version of .NET you need

  - script: dotnet build --configuration Release
    displayName: 'Build project'

  - script: dotnet test --configuration Release
    displayName: 'Run tests'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
